DreamCover/config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

root 'users#login_index'
   
#   ==============================Login Portions==================================================================

  get 'auth0_login' , to: "auth0#auth0_login", as: :auth0_login

  get '/auth/auth0/callback' => 'auth0#callback'

  get '/auth/failure' => 'auth0#failure'

  get '/auth/logout' => 'auth0#logout'

  get "/login", to: "users#login_index" , as: :login_index

  #---------------------------------Product and Product index--------------------------------------------------------
  
  get "/landing_page", to: "products#index" , as: :index 
   
   get "/product/product_index", to: "products#product_index", as: :product_index
   
   post "/products/all_product", to: "products#all_product"

   post "/products/new_arrival", to: "products#new_arrival"

   get "/products/featured_product",to: "products#featured_product"

   get "/products/single_product/:product_unique_id", to: "products#single_product", as: :single_product

   get "/products/new_product", to: "products#new_product",as: :new_product

   post "/products/create_product", to: "products#create_product",as: :create_product

   get "/products/edit_product/:product_unique_id", to: "products#edit_product",as: :edit_product

   put  "/products/update_product/:product_unique_id", to: "products#update_product",as: :update_product
   
   delete "/products/delete_product/:product_unique_id", to: "products#delete_product",as: :delete_product

       
   get "/products/search_result", to: "products#search_result",as: :search_result


   

  #--------------------------------------User--------------------------------------------------------
   get "/users/get_user", to: "users#user_index", as: :user_index

   get "/users/edit_user/:unique_id", to:  "users#edit_user", as: :edit_user

   put "/users/update_user/:unique_id", to:  "users#update_user",as: :update_user

   post "/users/create_user", to:  "users#create_user",as: :create_user

   post "/users/verify_user", to:  "users#verify_user",as: :verify_user

   post "/users/update_password", to:  "users#update_password",as: :update_password


   delete "/users/delete_user", to:  "user#delete_user"

   get "/get_states/:country", to: "users#get_states_by_country",as: :get_states

   get "/get_cities/:state", to: "users#get_cities_by_state", as: :get_cities

   
  
  #---------------------------------------cart----------------------------------------------------------


   post "/carts/cart_details/", to: "carts#cart_details"

   get "/carts/cart_index", to: "carts#cart_index", as: :cart_index

   post "/carts/add_to_cart/", to: "carts#add_to_cart"

   post "/carts/product_qauntity/", to: "carts#product_qauntity"

   get "/carts/new_cart", to:  "carts#new_cart"

   get "/carts/edit_cart", to:  "carts#edit_cart"

   put "/carts/update_cart", to:  "carts#update_cart"
   
   delete "/carts/delete_cart/:product_unique_id", to:  "carts#delete_cart"

   get "/carts/create_pay", to: "carts#create_pay"

     


   
  #---------------------------------------Payment----------------------------------------------------------
   get "/payments/get_payment", to: "payments#payment_index", as: :payment_index
   

   #--------------------------------------Contact and about-----------------------------------------------------------
   get "/products/contact", to: "products#contact_us", as: :contact_us 

   get "/products/about_us", to: "products#about", as: :about 

   # ===================================Wishlist======================================================

   post "/carts/wishlist_details/", to: "carts#wishlist_details"

   get "/carts/wishlist_index", to: "carts#wishlist_index", as: :wishlist_index

   get "/carts/delete_wishlist/:product_unique_id", to: "carts#delete_wishlist"

   post "/carts/add_to_wishlist/", to: "carts#add_to_wishlist"

# ---------------------------Order==========================================
   get "/orders/order_confirmation", to:  "orders#order_index", as: :order_index

   get "/invoice_generate", to: "orders#invoice_generate"
   
   get "/invoice_download", to: "orders#invoice_download", as: :invoice_download

# ---------------------------Delivery==========================================
   get "/orders/delivery_index", to:  "orders#delivery_index", as: :delivery_index

   post "/delivery/delivery_details/", to:  "deliveries#get_delivery"

   get "/orders/cancel_order", to:  "orders#cancel_order", as: :cancel_order

   post "/delivery/cancel_delivery", to: "deliveries#cancel_delivery"
 
# =============================================================================


# ================================================================================

   #---------------------------order-mailer-----------------------------------------
   post "/orders/create_order", to: "orders#create_order"
   #---------------------------delivery-mailer------------------------------------
   post "/deliveries/create_delivery", to: "deliveries#create_delivery"
   #---------------------------cart-mailer---------------------------------------
   post "/carts/create_cart", to: "carts#create_cart"


   get "/users/logout", to: "users#logout", as: :logout

   get "/new_user", to: "users#new_user", as: :new_user 

   get "/forget_password", to: "users#forget_password", as: :forget_password 

 #  ====================================================================


#  ---------------------------------Owner Routes-----------------------


get "/orders/order_log_index", to: "orders#order_log_index", as: :order_log_index

  get "/product_owner_index",to: "products#product_owner_index", as: :product_owner_index

  post "/products/products_for_owner", to: "products#products_for_owner"

  post "/order/get_order_logs", to: "orders#get_order_logs"


  # ===============================================

  get '/shipments/shipment', to: 'shipments#shipment_index', as: :shipment_index

  post '/shipments', to: 'shipments#create'

  # =============================================================================================

  get '/orders/new_incident', to: 'orders#new_incident', as: :new_incident

  get '/orders/incident_form', to: 'orders#incident_form', as: :incident_form
  

end

DreamCover/app/models/user.rb
class User < ApplicationRecord
    # has_many :addresses
	
	# has_one :return
	# has_many :orders
	# has_many :deliveries
	# has_many :cancellation

	# has_many :carts
	# has_many :products, through: :carts

    mount_uploader :file_extension, ImageUploader
	# validates_presence_of  :email
	validates_uniqueness_of :email  
	# ,conditions:->{where(is_active: true)} 
end

DreamCover/app/controllers/users_controller.rb
class UsersController < ApplicationController
	
    skip_before_action :verify_authenticity_token
	require 'securerandom'
    before_action :user_require, only:[:index,:new,:edit,:show]
    before_action :verify_authorization, only:[:new,:create,:index,:delete]


	def create_user
		byebug
		unique_id = SecureRandom.alphanumeric(20)
	 	cart_unique_id =  SecureRandom.alphanumeric(8)
		@user_info = ProductInformation::UserService.create_user(params["user"]["email"], params["user"]["password_digest"],  unique_id, cart_unique_id)
		if @user_info.errors.full_messages==[]
            session[:current_user_id] = @user_info.unique_id
            redirect_to user_index_path, notice: "New User Created Successfully"
        else
            render :login_index, status: :unprocessable_entity
        end
	end


	def update_password
		byebug
		@user_login =  ProductInformation::UserService.update_user_password(params[:email],params[:password_digest])
        
        if @user_login.nil? 
            @user_login =  "email-id Doesn't Exists"
            render :login_index, status: :unprocessable_entity

        elsif @user_login == false 
            @user_login = "Email id is exists, but Incorrect password"
            render :login_index, status: :unprocessable_entity

        else
            session[:current_user_id] = @user_login.unique_id
            session[:current_user_role] = @user_login.roles
			redirect_to index_path
        end
	end

	def verify_user
		# byebug
        @user_login =  ProductInformation::UserService.user_login(params[:email],params[:password_digest])
        
        if @user_login.nil? 
            @user_login =  "email-id Doesn't Exists"
            render :login_index, status: :unprocessable_entity

        elsif @user_login == false 
            @user_login = "Email id is exists, but Incorrect password"
            render :login_index, status: :unprocessable_entity

        else
            session[:current_user_id] = @user_login.unique_id
            session[:current_user_role] = @user_login.roles
			redirect_to index_path
        end

    end 


	def logout
		# byebug
		session.clear
		redirect_to login_index_path
	end
	




	def user_index
		# byebug
		@user_info = ProductInformation::UserService.get_user(session[:current_user_id])
		# @countries =CS.countries.find_by(@user_info.country)
		# @country= @user_info.country.invert
		# @states = CS.states(:us).invert
		# @cities =CS.cities(:ak, :us)
	end
		
	def login_index
		# byebug
		# redirect_to login_index_path
	end

	def new_user 
        @new_user = ProductInformation::UserService.new()
    end


	def edit_user
		# byebug
		@countries = CS.countries.invert
		@states = CS.states(:us).invert
		@cities =CS.cities(:ak, :us)
		email_id = $session_user
		
		@user_info =ProductInformation::UserService.edit_user(params[:unique_id])
	end

    def update_user
		# byebug
		@user_info= ProductInformation::UserService.update_user(params[:unique_id],user_params)
		redirect_to user_index_path
	end



	def delete_user
		@data=ProductInformation::UserService.delete_user(user_id)
	end

	def get_states_by_country
            country = (params[:country])
            @states = ProductInformation::UserService.get_states_by_country_id(country)
            render json: @states
    end

  	def get_cities_by_state
			state = (params[:state]) 
            @cities = ProductInformation::UserService.get_cities_by_state_id(state)
            render json: @cities
    end


	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :phone_number, :country, :city, :state, :file_extension, :cart_unique_id, :password_digest)
	end

end

DreamCover/app/helpers/users_helper.rb
module UsersHelper
end

DreamCover/app/views/users/edit_user.slim
body [ 
  data-controller = "user"
  ]
 = form_with  scope: @user_info, method: :put, url: update_user_path do |form|
    .container
      .row.gutters
        .col-xl-3.col-lg-3.col-md-12.col-sm-12.col-12
          .card-user.h-100
            .card-body
              .account-settings
                .user-profile
                  .user-avatar
                    img.rounded-circle[src= @user_info.file_extension alt="User Profile"]
                  h5.user-name
                      = @user_info.first_name =@user_info.last_name 
                  h6.user-email
                       = @user_info.email
                  h6.user-email
                       = @user_info.country
                
        .col-xl-9.col-lg-9.col-md-12.col-sm-12.col-12
          .card-user.h-100
            .card-body
              .row.gutters
                .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                  h6.mb-2.text-primary
                    | Personal Details
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="first_name"]  First Name
                    = form.text_field :first_name, class:"box-class", placeholder:"Enter First Name", id:"first_name", data: {"user-target" => "first_name" , action: "focusout->user#first_name_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="last_name"]  Last Name
                    = form.text_field :last_name, class:"box-class", placeholder:"Enter Last Name", id:"last_name", data: {"user-target" => "last_name" , action: "focusout->user#last_name_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="phone"]  Phone Number
                    = form.text_field :phone_number, class:"box-class", placeholder:"Enter Phone Number", id:"phone",maxlength:"10", data: {"user-target" => "phone_number" , action: "focusout->user#phone_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                 .form-group
                    label.lable-class[for="email"]  Email
                    = form.text_field :email, class:"box-class", placeholder:"Enter Email id", id:"email", data: {"hello-target" => "email" , action: "focusout->user#email_validation" }
              .row.gutters
                .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                  h6.mt-3.mb-2.text-primary
                    | Address
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="file"] Country
                    = form.select :country, @countries, {prompt: '---Select a Country---'} , class:"box-class dropdown-toggle", id:"country", data: {"user-target" => "country" , action: "click->user#country_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="file"]  State
                    = form.select :state,  @states , {prompt:'---Select a State---'} , class:"box-class dropdown-toggle",  id:"state", data: {"user-target" => "state" , action: "click->user#state_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="file"] City
                    = form.select :city,  @cities , {prompt: '---Select a City---'}, class:"box-class dropdown-toggle", id:"city", data: {"user-target" => "city" , action: "click->user#city_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="file"]  Zip Code
                    = form.text_field :pincode, class:"box-class", placeholder:"Enter Zipcode", id:"zipcode", data: {"user-target" => "zipcode" , action: "focusout->user#zipcode_validation" }
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="file"]  Image
                    = form.file_field :file_extension, class:"box-class", placeholder:"Add File ", id:"file"
              .row.gutters
                .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                  .text-right
                    .right_align
                        = form.button class:'btn-success' ,style:"font-size:14px;     background: black;"
                    .right_align
                        a.hyper href="/users/get_user" type="button" class="btn btn-dark index-anch" style="font-size: 14px;border-radius: 33px;     font-weight: bold;"  Cancel 

DreamCover/app/views/users/forget_password.html.slim
.parent-container[
    data-controller='user'
    ]
  = form_with scope: @new_user, method: :post, url: update_password_path  do |form|
    ul
        -unless @new_user.nil?
          .alert.alert-danger[
            data-user-target="notice_message"
            style="display:none"
            ]= @login_error 
        

    section.vh-100.gradient-custom 
      .container.py-3.h-100
        .row.d-flex.justify-content-center.align-items-center.h-100
          .col-12.col-md-8.col-lg-6.col-xl-5
            .card.bg-dark.text-white style=("border-radius: 1rem;") 
              .card-body.p-5.text-center
                .mb-md-4.mt-md-2
                  h2.fw-bold.mb-2.text-uppercase Forget Password
                  -unless @user.nil?
                    .alert.alert-primary.text-uppercase
                      | Welcome  
                      = (@user['nickname'])
                  .form-outline.form-white.mb-4
                    label.lable-class for="typeEmailX"  Email 
                    = form.email_field :email, type:"email", placeholder:"enter email id", id:"typeEmailX" , data: {"vendorform-target" => "login_email_id" , action: "focusout->vendorform#login_email_id_validation" }
                    label.err[
                      data-user-target='login_email_id_error'
                      style="display:none"
                      ] Email ID Required*
                  .form-outline.form-white.mb-4
                    label.lable-class for="pword"  New Password 
                    = form.password_field :password_digest, type:"password", placeholder:"enter password", id:"pword", data: {"vendorform-target" => "login_password" , action: "focusout->vendorform#login_password_validation" }
                    label.err[
                      data-user-target='login_password_error'
                      style="display:none"
                      ] password Required*
                  .form-outline.form-white.mb-4
                    label.lable-class for="pword"  Confirm New Password
                    = form.password_field :password_digest, type:"password", placeholder:"confirm password", id:"r-pword", data: {"vendorform-target" => "r_login_password" , action: "focusout->vendorform#login_r_password_validation" }
                    label.err[
                      data-user-target='login_r_password_error'
                      style="display:none"
                      ] re-enter the password*
                  .form-outline.form-white.mb-4
                    = form.submit  class:'btn btn-outline-light btn-lg login-button' , id:"btn" , value:"Update Password" ,style:"  width: 150px;", data: {action: 'click-> vendorform#login_validation'}
                      label.login-success-lable[
                          data-user-target="login_error"
                              ]
                  div
                    p.mb-0
                      h6 Already have an account, please login here ⬇
                      a.text-white-50.fw-bold href="/login"  Sign In 
                  

























/ - content_for :legacy_javascripts do
/   javascript:
/       $(document).ready(function(){
/                   console.log("hello")
/         $("#btn").click(function(event){
/           if(document.getElementById(email).value==""){
/               event.preventDefault();
/               $(err).show();

/           }
/           if(document.getElementById(pword).value==""){
/               event.preventDefault();
/               $(err).show();
         
/         });
/       });

DreamCover/app/views/users/login_index.html.slim
.parent-container[
  data-controller='user'
  ]
 =form_with scope: @user_info, method: :post, url: verify_user_path  do |form|
  ul
    -unless @user_login.nil?
      .alert.alert-danger.mt-4[
        data-user-target="notice_message"
        ]=@user_login

      -flash.each do |type,msg|
        .alert.alert-info.mt-4[
          data-user-target="notice_message"
          ]= msg

  section.gradient-custom 
    .container.py-5.h-100
      .row.d-flex.justify-content-center.align-items-center.h-100
        .col-12.col-md-8.col-lg-6.col-xl-5
          .card.bg-dark.text-white style=("border-radius: 1rem;") 
            .card-body.text-center
              .mb-md-5.mt-md-4
               .form-outline.form-white.mb-4
                img src="/assets/logo_1.png" style="width: 90px; height: 86px; border-radius: 171px;"
                h2.fw-bold.mb-2.text-uppercase Login Page
                p.text-white-40.mb-4.mt-3 Please enter your login and password!
                .form-outline.form-white.mb-4
                  label.lable-class for="typeEmailX"  Email 
                  = form.email_field :email, class:"",type:"email", placeholder:"enter email id", id:"typeEmailX" , data: {"vendorform-target" => "login_email_id" , action: "focusout->vendorform#login_email_id_validation" }
                  label.err[
                    data-user-target='login_email_id_error'
                    style="display:none"
                    ] Email ID Required*
                .form-outline.form-white.mb-4 
                  label.lable-class for="pword"  Password  
                  = form.password_field :password_digest, class:"",type:"password", placeholder:"enter password", id:"pword", data: {"vendorform-target" => "login_password" , action: "focusout->vendorform#login_password_validation" }
                  label.err[
                    data-user-target='login_password_error'
                    style="display:none"
                    ] password Required*
                .form-outline.form-white.mb-4  
                  = form.submit  class:'btn btn-outline-light btn-lg login-button' , id:"btn" , value:"Sign In"
                p.mb-0
                  a.text-white-50.fw-bold href="/forget_password"  Forget password ?
                p.mb-0
                  | Don't have an account?
                  a.text-white-50.fw-bold href="/new_user"  Sign Up
          
                
              

DreamCover/app/views/users/new_user.html.slim
.parent-container[
    data-controller='user'
    ]
  = form_with scope: @new_user, method: :post, url: create_user_path  do |form|
    ul
        -unless @new_user.nil?
          .alert.alert-danger[
            data-user-target="notice_message"
            style="display:none"
            ]= @login_error 
        

    section.vh-100.gradient-custom 
      .container.py-3.h-100
        .row.d-flex.justify-content-center.align-items-center.h-100
          .col-12.col-md-8.col-lg-6.col-xl-5
            .card.bg-dark.text-white style=("border-radius: 1rem;") 
              .card-body.p-5.text-center
                .mb-md-4.mt-md-2
                  h2.fw-bold.mb-2.text-uppercase Sign Up Page
                  p.text-white-40.mb-4.mt-3 Please enter your email and password!
                  -unless @user.nil?
                    .alert.alert-primary.text-uppercase
                      | Welcome  
                      = (@user['nickname'])
                  .form-outline.form-white.mb-4
                    label.lable-class for="typeEmailX"  Email 
                    = form.email_field :email, type:"email", placeholder:"enter email id", id:"typeEmailX" , data: {"vendorform-target" => "login_email_id" , action: "focusout->vendorform#login_email_id_validation" }
                    label.err[
                      data-user-target='login_email_id_error'
                      style="display:none"
                      ] Email ID Required*
                  .form-outline.form-white.mb-4
                    label.lable-class for="pword"  Password 
                    = form.password_field :password_digest, type:"password", placeholder:"enter password", id:"pword", data: {"vendorform-target" => "login_password" , action: "focusout->vendorform#login_password_validation" }
                    label.err[
                      data-user-target='login_password_error'
                      style="display:none"
                      ] password Required*
                  .form-outline.form-white.mb-4
                    label.lable-class for="pword"  Confirm Password
                    = form.password_field :password_digest, type:"password", placeholder:"confirm password", id:"r-pword", data: {"vendorform-target" => "r_login_password" , action: "focusout->vendorform#login_r_password_validation" }
                    label.err[
                      data-user-target='login_r_password_error'
                      style="display:none"
                      ] re-enter the password*
                  .form-outline.form-white.mb-4
                    = form.submit  class:'btn btn-outline-light btn-lg login-button' , id:"btn" , value:"Sign Up" , data: {action: 'click-> vendorform#login_validation'}
                      label.login-success-lable[
                          data-user-target="login_error"
                              ]
                div
                  p.mb-0
                    h6 Already have an account, please login here ⬇
                    a.text-white-50.fw-bold href="/login"  Sign In 
                

























/ - content_for :legacy_javascripts do
/   javascript:
/       $(document).ready(function(){
/                   console.log("hello")
/         $("#btn").click(function(event){
/           if(document.getElementById(email).value==""){
/               event.preventDefault();
/               $(err).show();

/           }
/           if(document.getElementById(pword).value==""){
/               event.preventDefault();
/               $(err).show();
         
/         });
/       });


DreamCover/app/views/users/user_index.html.erb
    <div class="container">

        <div class="main-body">
       
     <!-- Breadcrumb -->
              <nav aria-label="breadcrumb" class="main-breadcrumb">
                <ol class="breadcrumb">
                  <li class="breadcrumb-item active" aria-current="page">User Profile</li>
                </ol>
              </nav>
              <!-- Breadcrumb -->
        
              <div class="row gutters-sm">
                <div class="col-md-4 mb-3">
                  <div class="card-user">
                    <div class="card-body">
                      <div class="d-flex flex-column align-items-center text-center">
                        <img src= "<%=@user_info.file_extension%>" alt="Admin" class="rounded-circle" width="150">
                        <div class="mt-3">
                          <h4 style="font-weight: bold;"><%= @user_info.first_name %>  <%= @user_info.last_name %></h4>
                          <p class="text-muted font-size-sm"><%= @user_info.email %></p>
                        </div>

                        <div class="card-user mt-3 card-social-width">
                            <ul class="list-group list-group-flush">
                             
                              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="text-secondary " >Check My Cart</h6>
                                <a  class="fas fa-shopping-cart user-anch-opt mb-0" href="/carts/cart_index"> Cart</a>
                              </li>
                              <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="text-secondary " >Check My Wishlist</h6>
                                <a  class="fas fa-heart mb-0 user-anch-opt" href="/carts/wishlist_index" > Wishlist</a>
                              </li>
                               <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h6 class="text-secondary " >Check My Delivery</h6>
                                <a  class="fas fa-truck mb-0 user-anch-opt" href="/orders/delivery_index" > Delivery</a>
                              </li>
                             <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                                <h5 class="text-secondary " >For any Queries</h5>
                                <a type="button" class="fas fa-question-circle mb-0 user-anch-opt" href="/orders/new_incident" > Help</a>
                              </li>
                            </ul>
                          </div>
                      </div>
                    </div>
                  </div>
                  
                </div>
                <div class="col-md-8">
                  <div class="card-user mb-3 card-left-height">
                    <div class="card-body">
                      <div class="row">
                        <div class="col-sm-3">
                          <h6  style="font-weight: bold;" class="mb-0">Full Name</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          <%= @user_info.first_name%> <%= @user_info.last_name%> 
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6  style="font-weight: bold;" class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                          <%= @user_info.email%>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6  style="font-weight: bold;" class="mb-0">Phone</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                         <%= @user_info.phone_number%>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-3">
                          <h6  style="font-weight: bold;" class="mb-0">Address</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">
                         <%= @user_info.city%> <%= @user_info.state%> <%= @user_info.country%>
                        </div>
                      </div>
                      <hr>
                      <div class="row">
                        <div class="col-sm-12">
                          <a href="/users/edit_user/<%=@user_info.unique_id%>" class="index-anch btn-info btn">Edit</a>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
    
            </div>
        </div>
        </div>