DreamCover/config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

root 'users#login_index'
   
#   ==============================Login Portions==================================================================

  get 'auth0_login' , to: "auth0#auth0_login", as: :auth0_login

  get '/auth/auth0/callback' => 'auth0#callback'

  get '/auth/failure' => 'auth0#failure'

  get '/auth/logout' => 'auth0#logout'

  get "/login", to: "users#login_index" , as: :login_index

  #---------------------------------Product and Product index--------------------------------------------------------
  
  get "/landing_page", to: "products#index" , as: :index 
   
   get "/product/product_index", to: "products#product_index", as: :product_index
   
   post "/products/all_product", to: "products#all_product"

   post "/products/new_arrival", to: "products#new_arrival"

   get "/products/featured_product",to: "products#featured_product"

   get "/products/single_product/:product_unique_id", to: "products#single_product", as: :single_product

   get "/products/new_product", to: "products#new_product",as: :new_product

   post "/products/create_product", to: "products#create_product",as: :create_product

   get "/products/edit_product/:product_unique_id", to: "products#edit_product",as: :edit_product

   put  "/products/update_product/:product_unique_id", to: "products#update_product",as: :update_product
   
   delete "/products/delete_product/:product_unique_id", to: "products#delete_product",as: :delete_product

       
   get "/products/search_result", to: "products#search_result",as: :search_result


   

  #--------------------------------------User--------------------------------------------------------
   get "/users/get_user", to: "users#user_index", as: :user_index

   get "/users/edit_user/:unique_id", to:  "users#edit_user", as: :edit_user

   put "/users/update_user/:unique_id", to:  "users#update_user",as: :update_user

   post "/users/create_user", to:  "users#create_user",as: :create_user

   post "/users/verify_user", to:  "users#verify_user",as: :verify_user

   post "/users/update_password", to:  "users#update_password",as: :update_password


   delete "/users/delete_user", to:  "user#delete_user"

   get "/get_states/:country", to: "users#get_states_by_country",as: :get_states

   get "/get_cities/:state", to: "users#get_cities_by_state", as: :get_cities

   
  
  #---------------------------------------cart----------------------------------------------------------


   post "/carts/cart_details/", to: "carts#cart_details"

   get "/carts/cart_index", to: "carts#cart_index", as: :cart_index

   post "/carts/add_to_cart/", to: "carts#add_to_cart"

   post "/carts/product_qauntity/", to: "carts#product_qauntity"

   get "/carts/new_cart", to:  "carts#new_cart"

   get "/carts/edit_cart", to:  "carts#edit_cart"

   put "/carts/update_cart", to:  "carts#update_cart"
   
   delete "/carts/delete_cart/:product_unique_id", to:  "carts#delete_cart"

   get "/carts/create_pay", to: "carts#create_pay"

     


   
  #---------------------------------------Payment----------------------------------------------------------
   get "/payments/get_payment", to: "payments#payment_index", as: :payment_index
   

   #--------------------------------------Contact and about-----------------------------------------------------------
   get "/products/contact", to: "products#contact_us", as: :contact_us 

   get "/products/about_us", to: "products#about", as: :about 

   # ===================================Wishlist======================================================

   post "/carts/wishlist_details/", to: "carts#wishlist_details"

   get "/carts/wishlist_index", to: "carts#wishlist_index", as: :wishlist_index

   get "/carts/delete_wishlist/:product_unique_id", to: "carts#delete_wishlist"

   post "/carts/add_to_wishlist/", to: "carts#add_to_wishlist"

# ---------------------------Order==========================================
   get "/orders/order_confirmation", to:  "orders#order_index", as: :order_index

   get "/invoice_generate", to: "orders#invoice_generate"
   
   get "/invoice_download", to: "orders#invoice_download", as: :invoice_download

# ---------------------------Delivery==========================================
   get "/orders/delivery_index", to:  "orders#delivery_index", as: :delivery_index

   post "/delivery/delivery_details/", to:  "deliveries#get_delivery"

   get "/orders/cancel_order", to:  "orders#cancel_order", as: :cancel_order

   post "/delivery/cancel_delivery", to: "deliveries#cancel_delivery"
 
# =============================================================================


# ================================================================================

   #---------------------------order-mailer-----------------------------------------
   post "/orders/create_order", to: "orders#create_order"
   #---------------------------delivery-mailer------------------------------------
   post "/deliveries/create_delivery", to: "deliveries#create_delivery"
   #---------------------------cart-mailer---------------------------------------
   post "/carts/create_cart", to: "carts#create_cart"


   get "/users/logout", to: "users#logout", as: :logout

   get "/new_user", to: "users#new_user", as: :new_user 

   get "/forget_password", to: "users#forget_password", as: :forget_password 

 #  ====================================================================


#  ---------------------------------Owner Routes-----------------------


get "/orders/order_log_index", to: "orders#order_log_index", as: :order_log_index

  get "/product_owner_index",to: "products#product_owner_index", as: :product_owner_index

  post "/products/products_for_owner", to: "products#products_for_owner"

  post "/order/get_order_logs", to: "orders#get_order_logs"


  # ===============================================

  get '/shipments/shipment', to: 'shipments#shipment_index', as: :shipment_index

  post '/shipments', to: 'shipments#create'

  # =============================================================================================

  get '/orders/new_incident', to: 'orders#new_incident', as: :new_incident

  get '/orders/incident_form', to: 'orders#incident_form', as: :incident_form
  

end

DreamCover/app/views/options/_footer.html.erb
   <!-- footer section starts  -->
 <% if session[:current_user_id].present? %>
<section class="footer">

    <div class="box-container">

        <div class="box">
            <img class="dream-logo-footer" src="/assets/logo_1.png" alt=""> 
            <div class="share">
                <a href="https://en-gb.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNjc1MzM2NTQ5LCJjYWxsc2l0ZV9pZCI6MjY5NTQ4NDUzMDcyMDk1MX0%3D" class="fab fa-facebook-f index-anch"></a>
                <a href="https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoiZW4ifQ%3D%3D%22%7D" class="fab fa-twitter index-anch"></a>
                <a href="https://www.instagram.com/accounts/login/?source=auth_switcher" class="fab fa-instagram index-anch"></a>
                <a href="https://in.linkedin.com/" class="fab fa-linkedin index-anch"></a>
            </div>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="#" class="index-anch links"> <i class="fas fa-phone"></i> +123-456-7890 </a>
            <a href="#" class="index-anch links"> <i class="fas fa-phone"></i> +111-222-3333 </a>
            <a href="#" class="index-anch links"> <i class="fas fa-envelope"></i> dreamcover@gmail.com </a>
            <a href="#" class="index-anch links"> <i class="fas fa-map-marker-alt"></i> mumbai, india - 400104 </a>
        </div>

        <div class="box">
            <h3>quick links</h3>
            <a href="/landing_page" class="links index-anch"> <i class="fas fa-arrow-right"></i> home </a>
            <a href="/product/product_index" class="links index-anch"> <i class="fas fa-arrow-right"></i> products </a>
            <a href="/products/about_us" class="links index-anch"> <i class="fas fa-arrow-right"></i> About </a>
        </div>


    </div>

    <div class="credit"> <span> <p>Copyright &copy; 2022 <a rel="nofollow" class="index-anch" href="/landing_page">Dream Cover</a>| all rights reserved</p> </span>  </div>

</section>
<% end %> 
<!-- footer section ends -->

DreamCover/app/views/options/_header.html.erb
 
<% if session[:current_user_role] == "admin" %>
    <!-- header 1 section starts -->
    <header class="header" data-controller="hello" >
    <% if session[:current_user_id].present? %>
        <a href="/landing_page" class=" header-title index-anch"> 
            <img class="dream-logo-header" src="/assets/logo_1.png" alt="">
        </a>

        <nav class="navbar-header">
            <a class="index-anch" href="/landing_page">home</a>
            <a class="index-anch" href="/product_owner_index">products</a>
            <a class="index-anch" href="/orders/order_log_index">Order Logs</a>
        </nav>

      <div class="icons" style="    margin-right: -255px;"> 
                <div class="fas fa-bars" id="menu-btn">
                </div> 
             
            
              <% if session[:current_user_id]!= nil %>
            
            
                 
                 
                <div class="cart_btn">
                  <%= link_to "", new_product_path, :method => :get,  class:"fa fa-plus cart_btn-link header-btn" %> 
                </div> 
                <div class="user_btn">
                  <%= link_to "", user_index_path, :method => :get,  class:"fas fa-user user_btn-link " %> 
                </div> 
              
                 <div class="user_btn">
                  <%= link_to "", logout_path,  :method => :get,  class:"fas fa-sign-out-alt user_btn-link", style: "text-decoration: none" %> 
                </div> 
                

            <% else %>
                <div class="search_btn">
                  <%= link_to "", search_result_path, :method => :get,  class:"fas fa-search search_btn-link" %> 
                </div>

                <div class="cart_btn">
                  <%= link_to "", cart_index_path, :method => :get,  class:"fas fa-shopping-cart cart_btn-link header-btn" %> 
                </div> 
              
                <%= button_to 'Login', '/login',:method => :get,class: " btn-login-header form  user_btn-link"%>   

            <% end %> 
        </div> 
    <% end %> 
    </header>
    <%else%>

     <header class="header" data-controller="hello" >
      <% if session[:current_user_id].present? %>
        <a href="/landing_page" class=" header-title index-anch"> 
            <img class="dream-logo-header" src="/assets/logo_1.png" alt="">
        </a>

        <nav class="navbar-header">
            <a class="index-anch" href="/landing_page">home</a>
            <a class="index-anch" href="/product/product_index">products</a>
            <a class="index-anch" href="/carts/wishlist_index">Wishlist</a>
            <a class="index-anch" href="/products/contact">Contact Us</a>
            <a class="index-anch" href="/products/about_us">About Us</a>
        </nav>

      <div class="icons"> 
                <div class="fas fa-bars" id="menu-btn">
                </div> 
            
              <% if session[:current_user_id]!= nil %>
          
                <div class="search_btn">
                  <%= link_to "", search_result_path, :method => :get,  class:"fas fa-search search_btn-link" %> 
                </div>
                <div class="cart_btn">
                  <%= link_to "", cart_index_path, :method => :get,  class:"fas fa-shopping-cart cart_btn-link header-btn" %> 
                </div> 
                <div class="user_btn">
                  <%= link_to "", user_index_path, :method => :get,  class:"fas fa-user user_btn-link" %> 
                </div> 
                <div class="user_btn">
                  <%= link_to "", logout_path,  :method => :get,  class:"fas fa-sign-out-alt user_btn-link", style: "text-decoration: none" %> 
                </div> 
              
                

            <% else %>
                <div class="search_btn">
                  <%= link_to "", search_result_path, :method => :get,  class:"fas fa-search search_btn-link" %> 
                </div>

                <div class="cart_btn">
                  <%= link_to "", cart_index_path, :method => :get,  class:"fas fa-shopping-cart cart_btn-link header-btn" %> 
                </div> 
              
                <%= button_to 'Login', '/login',:method => :get,class: " btn-login-header form  user_btn-link"%>   

            <% end %> 
        </div> 

        <% end %> 
     
    </header>
     <%end%>
    <!-- header 1 section ends -->

DreamCover/app/views/options/_pdf_footer.html.erb

    <div class="footer">
     
    </div>

DreamCover/app/views/options/_pdf_header.html.erb

    <div class="header">
     <div class="card-header p-4">
          <img style="width: 140px; margin-left: 361px; height: 125px;" src="/assets/logo_1.png" alt=""> 
      <img class="logo" src="https://example.com/logo.png">
      <p style="font-weight:bold">Dream Cover</p>
      <p> 29, Singla Street</p>
      <p>Sikeston,New Delhi 110034</p>
      <p>Phone:  +111-222-3333</p>
      <p>Email: dreamcover@gmail.com</p>
    </div>
