DreamCover/config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

root 'users#login_index'
   
#   ==============================Login Portions==================================================================

  get 'auth0_login' , to: "auth0#auth0_login", as: :auth0_login

  get '/auth/auth0/callback' => 'auth0#callback'

  get '/auth/failure' => 'auth0#failure'

  get '/auth/logout' => 'auth0#logout'

  get "/login", to: "users#login_index" , as: :login_index

  #---------------------------------Product and Product index--------------------------------------------------------
  
  get "/landing_page", to: "products#index" , as: :index 
   
   get "/product/product_index", to: "products#product_index", as: :product_index
   
   post "/products/all_product", to: "products#all_product"

   post "/products/new_arrival", to: "products#new_arrival"

   get "/products/featured_product",to: "products#featured_product"

   get "/products/single_product/:product_unique_id", to: "products#single_product", as: :single_product

   get "/products/new_product", to: "products#new_product",as: :new_product

   post "/products/create_product", to: "products#create_product",as: :create_product

   get "/products/edit_product/:product_unique_id", to: "products#edit_product",as: :edit_product

   put  "/products/update_product/:product_unique_id", to: "products#update_product",as: :update_product
   
   delete "/products/delete_product/:product_unique_id", to: "products#delete_product",as: :delete_product

       
   get "/products/search_result", to: "products#search_result",as: :search_result


   

  #--------------------------------------User--------------------------------------------------------
   get "/users/get_user", to: "users#user_index", as: :user_index

   get "/users/edit_user/:unique_id", to:  "users#edit_user", as: :edit_user

   put "/users/update_user/:unique_id", to:  "users#update_user",as: :update_user

   post "/users/create_user", to:  "users#create_user",as: :create_user

   post "/users/verify_user", to:  "users#verify_user",as: :verify_user

   post "/users/update_password", to:  "users#update_password",as: :update_password


   delete "/users/delete_user", to:  "user#delete_user"

   get "/get_states/:country", to: "users#get_states_by_country",as: :get_states

   get "/get_cities/:state", to: "users#get_cities_by_state", as: :get_cities

   
  
  #---------------------------------------cart----------------------------------------------------------


   post "/carts/cart_details/", to: "carts#cart_details"

   get "/carts/cart_index", to: "carts#cart_index", as: :cart_index

   post "/carts/add_to_cart/", to: "carts#add_to_cart"

   post "/carts/product_qauntity/", to: "carts#product_qauntity"

   get "/carts/new_cart", to:  "carts#new_cart"

   get "/carts/edit_cart", to:  "carts#edit_cart"

   put "/carts/update_cart", to:  "carts#update_cart"
   
   delete "/carts/delete_cart/:product_unique_id", to:  "carts#delete_cart"

   get "/carts/create_pay", to: "carts#create_pay"

     


   
  #---------------------------------------Payment----------------------------------------------------------
   get "/payments/get_payment", to: "payments#payment_index", as: :payment_index
   

   #--------------------------------------Contact and about-----------------------------------------------------------
   get "/products/contact", to: "products#contact_us", as: :contact_us 

   get "/products/about_us", to: "products#about", as: :about 

   # ===================================Wishlist======================================================

   post "/carts/wishlist_details/", to: "carts#wishlist_details"

   get "/carts/wishlist_index", to: "carts#wishlist_index", as: :wishlist_index

   get "/carts/delete_wishlist/:product_unique_id", to: "carts#delete_wishlist"

   post "/carts/add_to_wishlist/", to: "carts#add_to_wishlist"

# ---------------------------Order==========================================
   get "/orders/order_confirmation", to:  "orders#order_index", as: :order_index

   get "/invoice_generate", to: "orders#invoice_generate"
   
   get "/invoice_download", to: "orders#invoice_download", as: :invoice_download

# ---------------------------Delivery==========================================
   get "/orders/delivery_index", to:  "orders#delivery_index", as: :delivery_index

   post "/delivery/delivery_details/", to:  "deliveries#get_delivery"

   get "/orders/cancel_order", to:  "orders#cancel_order", as: :cancel_order

   post "/delivery/cancel_delivery", to: "deliveries#cancel_delivery"
 
# =============================================================================


# ================================================================================

   #---------------------------order-mailer-----------------------------------------
   post "/orders/create_order", to: "orders#create_order"
   #---------------------------delivery-mailer------------------------------------
   post "/deliveries/create_delivery", to: "deliveries#create_delivery"
   #---------------------------cart-mailer---------------------------------------
   post "/carts/create_cart", to: "carts#create_cart"


   get "/users/logout", to: "users#logout", as: :logout

   get "/new_user", to: "users#new_user", as: :new_user 

   get "/forget_password", to: "users#forget_password", as: :forget_password 

 #  ====================================================================


#  ---------------------------------Owner Routes-----------------------


get "/orders/order_log_index", to: "orders#order_log_index", as: :order_log_index

  get "/product_owner_index",to: "products#product_owner_index", as: :product_owner_index

  post "/products/products_for_owner", to: "products#products_for_owner"

  post "/order/get_order_logs", to: "orders#get_order_logs"


  # ===============================================

  get '/shipments/shipment', to: 'shipments#shipment_index', as: :shipment_index

  post '/shipments', to: 'shipments#create'

  # =============================================================================================

  get '/orders/new_incident', to: 'orders#new_incident', as: :new_incident

  get '/orders/incident_form', to: 'orders#incident_form', as: :incident_form
  

end

DreamCover/app/models/product.rb
class Product < ApplicationRecord
	# has_many :order_items, dependent: :destroy
	# has_many :orders, through: :order_items


	mount_uploader :product_image1, ProductUploader
	mount_uploader :product_image2, ProductUploader
	mount_uploader :product_image3, ProductUploader
	mount_uploader :product_image4, ProductUploader
	mount_uploader :product_image5, ProductUploader

	

end

DreamCover/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	
	skip_before_action :verify_authenticity_token
	
	def index
		@data=Product.all
		
	end

	def all_product
		# byebug
		@informations,@total_count = ProductInformation::ProductService.get_all_products(params[:load_count].to_i,params[:search_text])
		render json: [@informations,@total_count]
	end

	def products_for_owner
		# byebug
		user_id = session[:current_user_id]
		@informations,@total_count = ProductInformation::ProductService.products_for_owner(params[:search_text],user_id)
		render json: [@informations,@total_count]
	end


	def new_arrival
		# byebug
		@informations, @total_count = ProductInformation::ProductService.new_arrivals(params[:load_count].to_i,params[:search_text])	
		render json: [@informations,@total_count]
	end

	def featured_product
		# byebug

		@featured_product = Product.last
		render json: @featured_product
	end

	def single_product
		# byebug
		@single_product = ProductInformation::ProductService.single_product(params[:product_unique_id])
		@user_info = ProductInformation::UserService.get_user(session[:current_user_id])
	end

	def new_product
		@product_info=ProductInformation::ProductService.new_product
	end

	def create_product
		# byebug
		user_id = session[:current_user_id]
		@product_info = ProductInformation::ProductService.create_product(parameters,user_id)
		redirect_to product_owner_index_path
	end

	def edit_product
		@product_info=ProductInformation::ProductService.edit_product(params[:product_unique_id])
	end

	def update_product
		# byebug
		@product_info=ProductInformation::ProductService.update_product(params[:product_unique_id],parameters)
		redirect_to product_owner_index_path
	end


	def delete_product
		# byebug
		@product_info=ProductInformation::ProductService.delete_product(params[:product_unique_id])
		render json: @product_info
	end


	private
	
	def parameters
		params.require(:product).permit(:product_name, :product_code,:product_price, :product_size, :product_image1, :product_image2, :product_image3, :product_image4, :product_image5, :product_cart_id, :product_description, :product_image2)
	end
end

DreamCover/app/helpers/products_helper.rb
module ProductsHelper
end

DreamCover/app/views/products/_form.html.slim
 =form_with  scope: product, method: method, class: "product-form", url: path do |form|
 
     .col-xl-9.col-lg-9.col-md-12.col-sm-12.col-12
          .card-user-product.h-100
            .card-body-product
              .row.gutters
                .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                  h6.mb-2.text-primary
                    | Product Details
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="name"]  Product Name
                    = form.text_field :product_name, class:"box-class-product-t", placeholder:"Enter Product Name", id:"name", data: {"user-target" => "name" , action: "focusout->user#product_name_validation" } ,style:" width: -webkit-fill-available;"
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="size"]  Product Size
                    = form.text_field :product_size, class:"box-class-product-t",required: "required", placeholder:"Enter Product size",  id:"size", data: {"user-target" => "color" , action: "focusout->user#color_validation" } ,style:" width: -webkit-fill-available;"
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                 .form-group
                    label.lable-class[for="price"]  Product Price
                    = form.text_field :product_price, class:"box-class-product-t",required: "required", placeholder:"Enter  Product Price", id:"price", data: {"user-target" => "price" , action: "focusout->user#price_validation" } ,style:" width: -webkit-fill-available;"
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="desc"] Product Description
                    = form.text_area  :product_description, class:"box-class-product",placeholder:"Enter Product Description", id:"description", maxlength:"250",data: {"user-target" => "description" , action: "focusout->user#state_validation" } ,style:" width: -webkit-fill-available;"
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                  .form-group
                    label.lable-class[for="image"]  Image 1
                    = form.file_field :product_image1, class:"box-class-product", placeholder:"Add File ", id:"file",style:" width: -webkit-fill-available;"
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                    .form-group
                      label.lable-class[for="image"]  Image 2
                      = form.file_field :product_image2, class:"box-class-product", placeholder:"Add File ", id:"file",style:" width: -webkit-fill-available;"
              
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                    .form-group
                      label.lable-class[for="image"]  Image 3
                      = form.file_field :product_image3, class:"box-class-product", placeholder:"Add File ", id:"file",style:" width: -webkit-fill-available;"

                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                    .form-group
                      label.lable-class[for="image"]  Image 4
                      = form.file_field :product_image4, class:"box-class-product", placeholder:"Add File ", id:"file",style:" width: -webkit-fill-available;"
                
                .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                    .form-group
                      label.lable-class[for="image"]  Image 5
                      = form.file_field :product_image5, class:"box-class-product", placeholder:"Add File ", id:"file" ,style:" width: -webkit-fill-available;"
              
              
              .row.gutters
                .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                  .text-right
                    .right_align
                        = form.button class:'btn-success' ,style:"font-size:20px;     background: black;"
                    .right_align
                        a.hyper href="/product_owner_index" class="btn btn-dark index-anch" style="font-size: 14px;border-radius: 33px;" Cancel 

DreamCover/app/views/products/about.html.erb
<!-- about section starts  -->

<section class="about" id="about">

    <h1 class="heading"> <span> about </span> us </h1>

    <div class="row">

        <div class="video-container">
            <img src="/assets/bed-sheet-1.jpg"  style="width: 500px; height: 400px;">
            <h3>best Bedsheet seller</h3>
        </div>

        <div class="content">
            <h3>why choose us?</h3>
            <p>These bedsheets simply change the look of your bedrooms. So welcoming you will always wish to get into bed. So many colors to choose from .Buying one is imperative

</p>
            <p>So affordable, you will be surprised. Sleep in the best only.Sleep the most and yet remain equally refreshed.</p>
        </div>

    </div>

</section>

<!-- about section ends -->

DreamCover/app/views/products/autho_login.html.slim
  section.vh-100.gradient-custom 
    .container.py-5.h-100
      .row.d-flex.justify-content-center.align-items-center.h-100
        .col-12.col-md-8.col-lg-6.col-xl-5
          .card.bg-dark.text-white style=("border-radius: 1rem;") 
            .card-body.p-5.text-center
              .mb-md-5.mt-md-4
                h2.fw-bold.mb-2.text-uppercase.font Vendor Management Application
                h2.fw-bold.mb-2.text-uppercase Auth0 Login Page
              
              div
              = button_to 'Auth0 Login', '/auth/auth0', method: :post , data: { turbo: "false" } , class:'btn btn-outline-info  btn-lg px-5'

DreamCover/app/views/products/contact_us.html.erb
<!-- contact section starts  -->

<section class="contact" id="contact">

    <h1 class="heading"> <span> contact </span> us </h1>

    <div class="row">

        <form action="">
            <input type="text" placeholder="First Name" class="box">
            <input type="text" placeholder="Last Name" class="box">
            <input type="email" placeholder="Email" class="box">
             <input type="text" placeholder="Phone Number" class="box" maxlength="10">
             <input type="file" class="box">
            <textarea name="" class="box" placeholder="Message" id="" cols="30" rows="10" maxlength="100"></textarea>
            <button type="button" class=" btn-lg btn btn-secondary">Send Message</button>
        </form>

        <div class="image-about">
            <img src="/assets/contact.jpg" alt="">
        </div>

    </div>

</section>

<!-- contact section ends -->

DreamCover/app/views/products/edit_product.html.erb
<%= render "form", product: @product_info, method: :put, path: update_product_path %>

DreamCover/app/views/products/index.html.erb
<body  data-controller = "product">

<!-- home section starts  -->

<section class="home-index" id="home">

    <div class="content">
        <h3>New </span> products for your</h3>
        <p></p>
 
    <%= link_to "View more", product_index_path, :method => :get,  class:"btn-index index-anch" %> 

    </div>

</section>


<!-- home section ends -->


<!-- products section starts  -->

<section class="products" id="products">

    <h1 class="heading"> our <span>products</span> </h1>

    <div class="swiper product-slider swiper-initialized swiper-horizontal swiper-pointer-events">

        <div class="swiper-wrapper">

            <div class="swiper-slide box swiper-slide-duplicate"style="width: 393px; margin-right: 20px;">
                <img src="/assets/bed-sheet-2.jpg" alt="">
                <h3>King Size</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                </div>
                  <%= link_to "View more", product_index_path, :method => :get,  class:"btn-index index-anch" %> 
                <!--<%= button_to "View more",product_index_path, :method => :get,  class:"btn-index index-anch",  value:"King" , data: {"product-target" => "king_size_product" , action: "click->product#new_arrival_products_dynamic_admin" }%>
                <button value="king" class="btn-index index-anch" data-action= "click->product#new_arrival_products_dynamic_admin"  >View More2 </button>-->
            </div>

             <div class="swiper-slide box swiper-slide-duplicate"style="width: 393px; margin-right: 20px;">
                <img src="/assets/bed-sheet-3.jpg" alt="">
                <h3>Queen Size</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                </div>
                <%= link_to "View more", product_index_path, :method => :get,  class:"btn-index index-anch" %> 
                <!--<%= button_to "View more",product_index_path, :method => :get,  class:"btn-index index-anch",  value:"Queen" , data: {"product-target" => "queen_size_product" , action: "click->product#new_arrival_products_dynamic_admin" }%>-->
            </div>

           <div class="swiper-slide box swiper-slide-duplicate"style="width: 393px; margin-right: 20px;">
                <img src="/assets/bed-sheet-6.jpg" alt="">
                <h3>Kid Size</h3>
                <div class="stars">
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star"></i>
                    <i class="fas fa-star-half-alt"></i>
                </div>
                <%= link_to "View more", product_index_path, :method => :get,  class:"btn-index index-anch" %> 
                   <!--<%= button_to "View more",product_index_path, :method => :get,  class:"btn-index index-anch",  value:"Kid" , data: {"product-target" => "kid_size_product" , action: "click->product#new_arrival_products_dynamic_admin" }%>-->
            </div>

        </div>

    </div>

</section>
<section class="deal" id="deal">
    
    <div class="icons-container">
    
        <div class="icons">
            <i class="fas fa-shipping-fast"></i>
            <h3>fast delivery</h3>
            <p>We make deliveries fast, so you can get back to other stuff faster 😉</p>
        </div>

    
        <div class="icons">
            <i class="fas fa-money-check-alt"></i>
            <h3>easy payments</h3>
            <p>Success is one thing you can't pay for. You buy it on the installment plan and make payments everyday</p>
        </div>
    
        <div class="icons">
            <i class="fas fa-box"></i>
            <h3>7 days replacements</h3>
            <p>Patch the uniform and let the galaxy form a comfortable replacement</p>
        </div>
    
    </div>
    
    </section>

<!-- products section ends -->


<!-- categories section starts  -->

    
</body>

DreamCover/app/views/products/login.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script
             src="https://kit.fontawesome.com/64d58efce2.js"
             crossorigin="anonymous"
             ></script>
             <title>Sign In & Sign Up Form</title>
             <link rel="stylesheet" href="css/login-page.css" />
    </head>
    <body>
    	<div class="alert alert-warning alert-dismissible fade show" role="alert">
  	<strong>Holy guacamole!</strong> You should check in on some of those fields below.
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
	</div>
        <div class="container-login">
            <div class="forms-container">
            <div class="signin-signup">
            <form action="#" class="sign-in-form login-form">
                <h2 class="title">Sign in</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                        <input type="text" placeholder="Username" />
        </div>
        <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" placeholder="Password" />
        </div>
        <a href="user_page.html" class="btn-solid">Login</a>
        <p class="social-text">Or Sign in with social platforms</p>
        <div class="social-media">
            <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
            </a>    
            </div>
            </form>
            <form action="#" class="sign-up-form">
                <h2 class="title">Sign up</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                        <input type="text" placeholder="Username" />
        </div>
        <div class="input-field">
            <i class="fas fa-envelope"></i>
                <input type="email" placeholder="Email" />
            </div>  
        <div class="input-field">
            <i class="fas fa-lock"></i>
            <input type="password" placeholder="Password" />
        </div>
        <a href="user_page.html" class="btn-solid">Sign Up</a>
        <p class="social-text">Or Sign up with social platforms</p>
        <div class="social-media">
            <a href="#" class="social-icon">
                <i class="fab fa-facebook-f"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-twitter"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-google"></i>
            </a>    
            <a href="#" class="social-icon">
                <i class="fab fa-linkedin-in"></i>
            </a>    
         </div>
      </form>
    </div>
  </div>
            <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>New To Here?</h3>
                    <p>Hey! Welcome To Our Dream Cover 
                        Make Your Dream To Cream</p>
                    <button class="btn transparent" id="sign-up-btn">
                        Sign up
                    </button>
            </div>
            <img src="img/register.svg" class="image" alt="" />
            </div>
                <div class="panel right-panel">
                    <div class="content">
                        <h3>One of us</h3>
                        <p>Hey! Welcome To Our Dream Cover 
                            Make Your Dream To Cream</p>
                        <button class="btn transparent" id="sign-in-btn">
                            Sign in
                        </button>
                </div>
                <img src="img/log.svg" class="image" alt="" /> 
            </div>
            </div>
        </div>
        <script src="js/login.js"></script>
    </body>
</html>

DreamCover/app/views/products/new_product.html.erb
<%= render "form", product: @product_info, method: :post, path:create_product_path %>

DreamCover/app/views/products/product_index.html.erb
<div data-controller = "product" >
<!-- --------------------------------arrival section starts ------------------------------- -->

    <!--<section class="arrival" id="arrival" >

    <h1 class="heading"> <span>new arrivals</span> 
    <div class="box-container" data-product-target="newArrival"  ></div>
  
    </section>-->
    
    
    <!-- -----------------------------arrival section ends------------------------------------ -->
    
    <!-- --------------------------featured section starts-----------------------------------  -->
    
    <section class="products-feature" id="featured">
    
     <h1 class="heading"> <span> New Arrival </span> </h1>
    
        <div class="products-feature-row" data-product-target="featuredProduct">
            
            
            
        </div>
    </section>
    
    <!-- -------------------------------------featured section ends -------------------------------->
    
    <!-- --------------------------------------gallery section starts----------------------------  -->
    
   

    <section class="featured" id="featured" >

    <h1 class="heading"> <span> products gallery </span> </h1>

    <div class="row"  data-product-target="productGallery">
      
    </div>

    </section>  
    
    <!-- ------------------------------------gallery section ends-------------------------- -->
    
    <!-- --------------------------------deal section starts--------------------------  -->
    
   
    
    <!-- -----------------------------------------deal section ends------------------------------------ -->

</div>




   

DreamCover/app/views/products/product_owner_index.html.erb
<!-- featured section starts  -->
<div data-controller="product-owner">
 <div class=" d-flex justify-content-center align-items-center" style="margin-top: 130px;">
            <div class="col-md-6">
                <div class="form-search">
                  <i class="fa fa-search"></i>
                  <input type="text" class="form-control form-input" placeholder="Search anything..." data-action="input->product-owner#search_box" data-product-owner-target="searchText" >
                </div>    
            </div> 
        </div>
<section class="featured" id="featured" >

    <h1 class="heading"> <span>All</span> products </h1>

    <div class="row"  data-product-owner-target="productGallery">
      
    </div>

</section>
</div>

<!-- featured section ends -->

DreamCover/app/views/products/search_result.html.erb
<div class="container-search" data-controller = "search" >
<!-- --------------------------------arrival section starts ------------------------------- -->
      <div class=" d-flex justify-content-center align-items-center" style="margin-top: 130px;">
            <div class="col-md-6">
                <div class="form-search">
                  <i class="fa fa-search"></i>
                  <input type="text" class="form-control form-input" placeholder="Search anything..." data-action="input->search#search_box" data-search-target="searchText" >
                </div>    
            </div> 
        </div>


    <section class="featured" id="featured" >

        <h1 class="heading"> <span>Search</span> Results </h1>

        <div class="row"  data-search-target="serachData">
        
        </div>


        <div class="alert alert-success" role="alert" data-search-target="searchError">
            <h4 class="alert-heading">Product Search Column!</h4>
            <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>
            <hr>
            <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>
        </div>
    
    </section>
</div>