DreamCover/config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin_users, ActiveAdmin::Devise.config
#   ActiveAdmin.routes(self)

root 'users#login_index'
   
#   ==============================Login Portions==================================================================

  get 'auth0_login' , to: "auth0#auth0_login", as: :auth0_login

  get '/auth/auth0/callback' => 'auth0#callback'

  get '/auth/failure' => 'auth0#failure'

  get '/auth/logout' => 'auth0#logout'

  get "/login", to: "users#login_index" , as: :login_index

  #---------------------------------Product and Product index--------------------------------------------------------
  
  get "/landing_page", to: "products#index" , as: :index 
   
   get "/product/product_index", to: "products#product_index", as: :product_index
   
   post "/products/all_product", to: "products#all_product"

   post "/products/new_arrival", to: "products#new_arrival"

   get "/products/featured_product",to: "products#featured_product"

   get "/products/single_product/:product_unique_id", to: "products#single_product", as: :single_product

   get "/products/new_product", to: "products#new_product",as: :new_product

   post "/products/create_product", to: "products#create_product",as: :create_product

   get "/products/edit_product/:product_unique_id", to: "products#edit_product",as: :edit_product

   put  "/products/update_product/:product_unique_id", to: "products#update_product",as: :update_product
   
   delete "/products/delete_product/:product_unique_id", to: "products#delete_product",as: :delete_product

       
   get "/products/search_result", to: "products#search_result",as: :search_result


   

  #--------------------------------------User--------------------------------------------------------
   get "/users/get_user", to: "users#user_index", as: :user_index

   get "/users/edit_user/:unique_id", to:  "users#edit_user", as: :edit_user

   put "/users/update_user/:unique_id", to:  "users#update_user",as: :update_user

   post "/users/create_user", to:  "users#create_user",as: :create_user

   post "/users/verify_user", to:  "users#verify_user",as: :verify_user

   post "/users/update_password", to:  "users#update_password",as: :update_password


   delete "/users/delete_user", to:  "user#delete_user"

   get "/get_states/:country", to: "users#get_states_by_country",as: :get_states

   get "/get_cities/:state", to: "users#get_cities_by_state", as: :get_cities

   
  
  #---------------------------------------cart----------------------------------------------------------


   post "/carts/cart_details/", to: "carts#cart_details"

   get "/carts/cart_index", to: "carts#cart_index", as: :cart_index

   post "/carts/add_to_cart/", to: "carts#add_to_cart"

   post "/carts/product_qauntity/", to: "carts#product_qauntity"

   get "/carts/new_cart", to:  "carts#new_cart"

   get "/carts/edit_cart", to:  "carts#edit_cart"

   put "/carts/update_cart", to:  "carts#update_cart"
   
   delete "/carts/delete_cart/:product_unique_id", to:  "carts#delete_cart"

   get "/carts/create_pay", to: "carts#create_pay"

     


   
  #---------------------------------------Payment----------------------------------------------------------
   get "/payments/get_payment", to: "payments#payment_index", as: :payment_index
   

   #--------------------------------------Contact and about-----------------------------------------------------------
   get "/products/contact", to: "products#contact_us", as: :contact_us 

   get "/products/about_us", to: "products#about", as: :about 

   # ===================================Wishlist======================================================

   post "/carts/wishlist_details/", to: "carts#wishlist_details"

   get "/carts/wishlist_index", to: "carts#wishlist_index", as: :wishlist_index

   get "/carts/delete_wishlist/:product_unique_id", to: "carts#delete_wishlist"

   post "/carts/add_to_wishlist/", to: "carts#add_to_wishlist"

# ---------------------------Order==========================================
   get "/orders/order_confirmation", to:  "orders#order_index", as: :order_index

   get "/invoice_generate", to: "orders#invoice_generate"
   
   get "/invoice_download", to: "orders#invoice_download", as: :invoice_download

# ---------------------------Delivery==========================================
   get "/orders/delivery_index", to:  "orders#delivery_index", as: :delivery_index

   post "/delivery/delivery_details/", to:  "deliveries#get_delivery"

   get "/orders/cancel_order", to:  "orders#cancel_order", as: :cancel_order

   post "/delivery/cancel_delivery", to: "deliveries#cancel_delivery"
 
# =============================================================================


# ================================================================================

   #---------------------------order-mailer-----------------------------------------
   post "/orders/create_order", to: "orders#create_order"
   #---------------------------delivery-mailer------------------------------------
   post "/deliveries/create_delivery", to: "deliveries#create_delivery"
   #---------------------------cart-mailer---------------------------------------
   post "/carts/create_cart", to: "carts#create_cart"


   get "/users/logout", to: "users#logout", as: :logout

   get "/new_user", to: "users#new_user", as: :new_user 

   get "/forget_password", to: "users#forget_password", as: :forget_password 

 #  ====================================================================


#  ---------------------------------Owner Routes-----------------------


get "/orders/order_log_index", to: "orders#order_log_index", as: :order_log_index

  get "/product_owner_index",to: "products#product_owner_index", as: :product_owner_index

  post "/products/products_for_owner", to: "products#products_for_owner"

  post "/order/get_order_logs", to: "orders#get_order_logs"


  # ===============================================

  get '/shipments/shipment', to: 'shipments#shipment_index', as: :shipment_index

  post '/shipments', to: 'shipments#create'

  # =============================================================================================

  get '/orders/new_incident', to: 'orders#new_incident', as: :new_incident

  get '/orders/incident_form', to: 'orders#incident_form', as: :incident_form
  

end

DreamCover/app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController

  require 'fedex'


        def shipment_index
        end


        def create
          byebug
          # Set up FedEx client
          fedex = Fedex::Shipment.new(
            :key => "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzY29wZSI6WyJDWFMiXSwiUGF5bG9hZCI6eyJjbGllbnRJZGVudGl0eSI6eyJjbGllbnRLZXkiOiJsN2YxYzFkMjMzMDA0YzQ3MTc5NTcwZGY3Y2FjOGEwOTA1In0sImF1dGhlbnRpY2F0aW9uUmVhbG0iOiJDTUFDIiwiYWRkaXRpb25hbElkZW50aXR5Ijp7InRpbWVTdGFtcCI6IjA3LU1hci0yMDIzIDA4OjA1OjI0IEVTVCIsImdyYW50X3R5cGUiOiJjbGllbnRfY3JlZGVudGlhbHMiLCJhcGltb2RlIjoiU2FuZGJveCIsImN4c0lzcyI6Imh0dHBzOi8vY3hzYXV0aHNlcnZlci1zdGFnaW5nLmFwcC5wYWFzLmZlZGV4LmNvbS90b2tlbi9vYXV0aDIifSwicGVyc29uYVR5cGUiOiJEaXJlY3RJbnRlZ3JhdG9yX0IyQiJ9LCJleHAiOjE2NzgxOTc5MjQsImp0aSI6IjhiODJlZDU2LWM5NDItNGNiYy04YWQ2LTJjNGFjZWIzOTNkZiJ9.V7ICawxEsc-CDuIqHehSuB42ugUratp3EUAqb-dx5Ame7pyxnJZraIhPAHmKiMOaiheU2HKIosuF0YkrZ-9FT5lu644QwAmTVDbS2Vs7yLP9e97SZE8UZYkXP0xQucSND4V2IMQZ_WPMEt9jXizXsCHV3k0EyCZi0KxAzczwQVKKtNz9CKXjBn29AignaDfyKSKPuCkZ2HT5YBX2vDPZ2cMVfkpYGa5lNItAMyVuB8MkWIyv8YA75qvjgefPNQrWb_FTbzfru3j_PyuwegGU8vkFJiPXXmnV1UmLSzbhh4zxNFkMer_BJDiJAYEFGFVqQAxeKZyoXRISVUp5ErapYm47sPgnB3IviWdExOJz3jo0meJjKgmY3rw5CyC6PuMu0UCPgADx6VIGFu6qp99rgR0MNgVau_O9OE_rYRur65FV5ebd9bQsvLSEKRUV7e357P8fpakLQrhb3-c9ZRXf-uvAIynE08AEAppJvQLOmb0A4F_-oIpMJd2lUVZ1DSnNQiUr2drm6JKXql9kn7FOvoWtSskENq09fLycT9uTy4cmJO8_JA7yPyVWsmOClmNHK3Kph0bXfPjHs8QuSsXbUk3hzHv0VKRC1cOAr5u7OIZlUdVE39lKGbl1EC2mVac8pCrhHHFOYqECEOkFE169i06BFb7cJANP7loTv3MrrZc",
            :password => 'YOUR_PASSWORD',
            :account_number => 'YOUR_ACCOUNT_NUMBER',
            :meter => 'YOUR_METER_NUMBER',
            :mode => 'test'
          )
      
          # Create shipment
          shipment = fedex.shipment(
            :shipper => {
              :name => 'Sender Name',
              :company => 'Sender Company',
              :phone_number => '555-555-5555',
              :address => {
                :line1 => '1234 Main St',
                :city => 'Anytown',
                :state => 'IL',
                :postal_code => '12345',
                :country_code => 'US'
              }
            },
            :recipient => {
              :name => 'Recipient Name',
              :company => 'Recipient Company',
              :phone_number => '555-555-5555',
              :address => {
                :line1 => '5678 Main St',
                :city => 'Anytown',
                :state => 'IL',
                :postal_code => '54321',
                :country_code => 'US'
              }
            },
            :packages => [
              {
                :weight => { :units => 'LB', :value => 10 },
                :dimensions => { :length => 10, :width => 10, :height => 10, :units => 'IN' }
              }
            ]
          )
      
          # Generate airway bill
          airway_bill = fedex.generate_shipping_document(:shipment => shipment, :type => 'AIR_WAYBILL')
      
          # Do something with airway bill (e.g. save to database, display to user)
          # ...
      
          # Redirect to a confirmation page
          redirect_to confirmation_path
        end


        def shipment_confirmation
          # Get the airway bill from the database or wherever you saved it
          airway_bill = # ...
      
          # Get any other relevant information that you want to display on the confirmation page
          # ...
      
          # Render the confirmation page
          render :shipment_confirmation, locals: { airway_bill: airway_bill, other_info: other_info }
        end

      
end

DreamCover/app/helpers/shipments_helper.rb
module ShipmentsHelper
end

DreamCover/app/views/shipments/shipment_confirmation.html.erb
<h1>Shipment Confirmation</h1>

<p>Your shipment has been created. The airway bill number is <%= airway_bill %>.</p>

<!-- Display any other relevant information here -->


DreamCover/app/views/shipments/shipment_index.html.slim
body
  = form_with(url: shipments_path, method: :post) do |form|
    .col-xl-9.col-lg-9.col-md-12.col-sm-12.col-12 style="margin-top: 122px;"
              .card-user.h-100
                .card-body
                  .row.gutters
                    .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                      h6.mb-2.text-primary
                        | Personal Details
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="first_name"]  Sender_name
                        = form.text_field :sender_name, class:"box-class", placeholder:"Enter First Name", id:"first_name", data: {"user-target" => "first_name" , action: "focusout->user#first_name_validation" }
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="last_name"]  recipient_name
                        = form.text_field :recipient_name , class:"box-class", placeholder:"Enter Last Name", id:"last_name", data: {"user-target" => "last_name" , action: "focusout->user#last_name_validation" }
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="phone"]  recipient_address
                        =  form.text_area :recipient_address , class:"box-class", placeholder:"Enter Phone Number", id:"phone",maxlength:"10", data: {"user-target" => "phone_number" , action: "focusout->user#phone_validation" }
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                    .form-group
                        label.lable-class[for="email"]  package_weight
                        = form.number_field :package_weight, class:"box-class", placeholder:"Enter Email id", id:"email", data: {"hello-target" => "email" , action: "focusout->user#email_validation" }
                  .row.gutters
                    .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                      h6.mt-3.mb-2.text-primary
                        | Address
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="file"] package_length
                        = form.number_field :package_length,class:"box-class dropdown-toggle"
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="file"]  package_width
                        = form.number_field :package_width,  class:"box-class dropdown-toggle"
                    .col-xl-6.col-lg-6.col-md-6.col-sm-6.col-12
                      .form-group
                        label.lable-class[for="file"] package_height
                        = form.number_field :package_height , class:"box-class dropdown-toggle"
                  .row.gutters
                    .col-xl-12.col-lg-12.col-md-12.col-sm-12.col-12
                      .text-right
                        .right_align
                            = form.button class:'btn-success' ,style:"font-size:14px;     background: black;"
                        .right_align
                            a.hyper href="/users/get_user" type="button" class="btn btn-dark index-anch" style="font-size: 14px;border-radius: 33px;     font-weight: bold;"  Cancel 